# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc4129ab2590371ad132e9309803f15d31ed2ecb23b42eb934041c0a22f9829de2e595051e479ce7175cdc757a2d4db1d1adfaf97590dc5978b4bb4474e0431f

test:
  secret_key_base: 4634a25166cdebb9aa247b66f9dc85d4c8923107312a7a2f3529395a6e20053e93e52ed961ce8e6f9577deb2342a6936142ed660d9504406eb3d6d9763e5fafd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
